# Generated by Django 4.2.4 on 2023-10-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pesquisa', '0002_remove_produto_id_produto_id_produto_produto_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
