# Generated by Django 4.2.4 on 2023-08-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_produto_lote_alter_produto_fab_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='lote',
        ),
    ]
