# Generated by Django 4.2.4 on 2023-08-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0003_remove_produto_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fab',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
