# Generated by Django 4.2.4 on 2023-09-14 13:34

from django.db import migrations, models
import pesquisa.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0004_alter_produto_fab_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pesquisa.models.upload_media),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fab',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
