# Generated by Django 4.2.4 on 2023-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0008_remove_produto_valor_alter_produto_fab'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fab',
            field=models.CharField(max_length=254),
        ),
    ]
