# Generated by Django 4.2.4 on 2023-10-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0010_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
