# Generated by Django 4.2.4 on 2023-10-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0011_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='emailUser',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeUser',
            field=models.TextField(max_length=255),
        ),
    ]
